language: cpp
sudo: false
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    compiler: clang
  - os: linux
    sudo: required
    dist: trusty
    compiler: gcc
#  - os: osx
#    compiler: clang
#  - os: osx
#    compiler: gcc
git:
  depth: 5
addons:
  apt:
    packages:
    - qt4-qmake
    - libqt4-dev
    - qt5-qmake
    - qtbase5-dev
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get install
  -y qt4-qmake libqt4-dev qt5-qmake qtbase5-dev; fi
#- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt4-qmake libqt4-dev; fi
install:
- git clone --quiet --depth 1 https://github.com/fifengine/fifengine-atlas-creator.git
- cd src; qmake-qt4
- make -j2
- sudo make install
- cd ..
script:
- cd ..
- cd src; qmake-qt4
- ls -alh .
- make -j2
- sudo make install
notifications:
  irc: irc.freenode.org#fife
  email: false
#deploy:
#  provider: releases
#  api_key:
#    secure: Bi5esH9G3mPpMdDAyVXsbrvoOhHm9lf38NBI5BR85GDuBg4gE3Gm8nlprBQWhm7jXSZH9qc58MeC48B4YWqA/TjVBRqJ2n+H0dK0jLUZi4yo1kB+bDxkshZP7GtAC62wUSKF81aPY38kH3yj8AR3iUHaYUBRc54BkeWzsvJ3C1g=
#  file: Fifengine*.tar.gz
#  on:
 #   repo: fifengine/fifengine
